export enum ActionType {
    CREATE = "CREATE",
    FETCH_ALL = "FETCH_ALL",
    DELETE = "DELETE",
    TOGGLE = "TOGGLE",
    SET_FILTER = "SET_FILTER",
    FILTER_ALL = "FILTER_ALL",
    FILTER_ACTIVE = "FILTER_ACTIVE",
    FILTER_COMPLETE = "FILTER_COMPLETE",
}